use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use board_model::Schemas;
use ech_db_entity::{BcsSchema, EntityId, EntitySchema, Schema, VariantSchema};

pub struct Frontend;

impl Frontend {
    pub fn source() -> String {
        let mut emitter = Emitter::new();
        for entity in Schemas::entities() {
            let _ = emitter.expr(&Self::record_schema(&entity));
        }
        for schema in Schemas::events() {
            let _ = emitter.expr(&schema);
        }
        let mut source = String::new();
        writeln!(source, "// generated by board-schema; do not edit").unwrap();
        writeln!(source, "import {{ bcs }} from '@mysten/bcs';").unwrap();
        writeln!(source).unwrap();
        for definition in &emitter.definitions {
            writeln!(source, "{definition}").unwrap();
        }
        writeln!(source).unwrap();
        let mut seen: BTreeSet<&String> = BTreeSet::new();
        for name in &emitter.order {
            if seen.insert(name) {
                writeln!(source, "export type {name} = typeof {name}.$inferType;").unwrap();
            }
        }
        source
    }

    fn state_schema(entity: &EntitySchema) -> Schema {
        Schema::Enum {
            name: entity.name.clone(),
            variants: entity
                .versions
                .iter()
                .map(|version| {
                    (
                        format!("V{}", version.version),
                        VariantSchema::Fields(
                            version
                                .fields
                                .iter()
                                .map(|field| (field.name.clone(), field.bcs.clone()))
                                .collect(),
                        ),
                    )
                })
                .collect(),
        }
    }

    fn record_schema(entity: &EntitySchema) -> Schema {
        Schema::Struct {
            name: format!("{}Record", entity.name),
            fields: vec![
                ("type_name".to_string(), Schema::String),
                (
                    "parent".to_string(),
                    Schema::Option(Box::new(<EntityId as BcsSchema>::schema())),
                ),
                ("state".to_string(), Self::state_schema(entity)),
            ],
        }
    }
}

struct Emitter {
    emitted: BTreeMap<String, String>,
    definitions: Vec<String>,
    order: Vec<String>,
}

impl Emitter {
    fn new() -> Self {
        Self {
            emitted: BTreeMap::new(),
            definitions: Vec::new(),
            order: Vec::new(),
        }
    }

    fn identifier(name: &str) -> String {
        let mut output = String::new();
        for character in name.chars() {
            if character.is_ascii_alphanumeric() || character == '_' {
                output.push(character);
            } else {
                output.push('_');
            }
        }
        output
    }

    fn named(&mut self, name: &str, body: impl FnOnce(&mut Self) -> String) -> String {
        let identifier = Self::identifier(name);
        if let Some(existing) = self.emitted.get(&identifier) {
            return existing.clone();
        }
        self.emitted.insert(identifier.clone(), identifier.clone());
        let expression = body(self);
        self.definitions
            .push(format!("export const {identifier} = {expression};"));
        self.order.push(identifier.clone());
        identifier
    }

    fn expr(&mut self, schema: &Schema) -> String {
        match schema {
            Schema::U8 => "bcs.u8()".to_string(),
            Schema::U16 => "bcs.u16()".to_string(),
            Schema::U32 => "bcs.u32()".to_string(),
            Schema::U64 => "bcs.u64()".to_string(),
            Schema::U128 => "bcs.u128()".to_string(),
            Schema::I8 => "bcs.i8()".to_string(),
            Schema::I16 => "bcs.i16()".to_string(),
            Schema::I32 => "bcs.i32()".to_string(),
            Schema::I64 => "bcs.i64()".to_string(),
            Schema::I128 => "bcs.i128()".to_string(),
            Schema::Bool => "bcs.bool()".to_string(),
            Schema::String => "bcs.string()".to_string(),
            Schema::Vector(item) => {
                let inner = self.expr(item);
                format!("bcs.vector({inner})")
            }
            Schema::FixedArray { len, item } => {
                let inner = self.expr(item);
                format!("bcs.fixedArray({len}, {inner})")
            }
            Schema::Option(item) => {
                let inner = self.expr(item);
                format!("bcs.option({inner})")
            }
            Schema::Tuple(items) if items.is_empty() => "bcs.struct('Unit', {})".to_string(),
            Schema::Tuple(items) => {
                let fields: Vec<String> = items
                    .iter()
                    .enumerate()
                    .map(|(index, item)| {
                        let inner = self.expr(item);
                        format!("f{index}: {inner}")
                    })
                    .collect();
                format!("bcs.struct('Tuple', {{ {} }})", fields.join(", "))
            }
            Schema::Struct { name, fields } => {
                let name = name.clone();
                let fields = fields.clone();
                self.named(&name, |emitter| {
                    let entries: Vec<String> = fields
                        .iter()
                        .map(|(field, schema)| {
                            let inner = emitter.expr(schema);
                            format!("{field}: {inner}")
                        })
                        .collect();
                    format!("bcs.struct({name:?}, {{ {} }})", entries.join(", "))
                })
            }
            Schema::Enum { name, variants } => {
                let name = name.clone();
                let variants = variants.clone();
                self.named(&name, |emitter| {
                    let entries: Vec<String> = variants
                        .iter()
                        .map(|(variant, shape)| match shape {
                            VariantSchema::Unit => format!("{variant}: null"),
                            VariantSchema::Fields(fields) => {
                                let struct_name = format!("{name}{variant}");
                                let entries: Vec<String> = fields
                                    .iter()
                                    .map(|(field, schema)| {
                                        let inner = emitter.expr(schema);
                                        format!("{field}: {inner}")
                                    })
                                    .collect();
                                format!(
                                    "{variant}: bcs.struct({struct_name:?}, {{ {} }})",
                                    entries.join(", ")
                                )
                            }
                        })
                        .collect();
                    format!("bcs.enum({name:?}, {{ {} }})", entries.join(", "))
                })
            }
            Schema::Newtype { name, inner } => {
                let name = name.clone();
                let inner = inner.clone();
                self.named(&name, |emitter| emitter.expr(&inner))
            }
        }
    }
}
